### ISSUE TITLE
[Search] UI 보완

### ISSUE THREAD

**Issue by NalaJang** [NalaJang/sample#21]
## 🌿  To-do

- [x] '저장' 버튼 색상 변경
- [x] 검색 결과 텍스트 스타일 변경
- [ ] 탄단지 그래프로 보여주기
- [x] 1회 제공량 표시
- [x] 인터넷 연결 코드 추가
